-- Script generated by SimpleSpy - credits to exx#9394
getgenv().npc = 'King Brian'
getgenv().item = "King's Crown"

Drawing.clear()
local remote = game:GetService("ReplicatedStorage").RemoteEvent
local contextactionservice = game:GetService("ContextActionService")
local players = game:GetService("Players")
local vy, vx = workspace.CurrentCamera.ViewportSize.Y, workspace.CurrentCamera.ViewportSize.X
local text = Drawing.new("Text")
text.Visible = true
text.Position = Vector2.new(vx / 2 - 30, vy / 2 + 200)
text.Color = Color3.fromRGB(255, 255, 255)
text.Text = 'press keypad one to start finding'
text.Size = 24
getgenv().stop = false
getgenv().currentCollector = false
getgenv().searchingCollector = false

local function handleAction(actionName, inputState, _inputObject)
	if actionName == 'stop_buying' and inputState == Enum.UserInputState.Begin then
		getgenv().stop = true
		wait()
		getgenv().stop = false
	end
	if actionName == 'sell_all' and inputState == Enum.UserInputState.Begin then
		if currentCollector ~= false and currentCollector.Parent:FindFirstChild(currentCollector.Name) then
			remote:FireServer("SellAllItems", currentCollector)
			text.Text = 'selling!'
		else
			currentCollector = false
			text.Text = 'no collector!'
		end
	end
	if actionName == 'buy_stuff' and inputState == Enum.UserInputState.Begin then
		for _,v in pairs(workspace:GetDescendants()) do
			-- Script generated by SimpleSpy - credits to exx#9394
			if getgenv().stop then
				text.Text = 'force stopped' 
				break 
			end
			local args = {
				[1] = "BuyItem",
				[2] = {
					[1] = getgenv.item,
					[2] = getgenv.npc,
					[3] = v
				}
			}

			remote:FireServer(unpack(args))
			task.wait()
		end

	end
	if actionName == 'find_collector' and inputState == Enum.UserInputState.Begin then
		if getgenv().searchingCollector == true then
			return
		end
		currentCollector = false
		getgenv().searchingCollector = true
		while currentCollector == false and task.wait() do
			for _,v in pairs(workspace.Storages:GetDescendants()) do
				if v.Name == 'The Collector' then
					players.LocalPlayer.Character:PivotTo(v:GetPivot() * CFrame.new(0, 2, 0))
					text.Text = 'found him!'
					currentCollector = v
					getgenv().searchingCollector = false
				end
			end
			text.Text = 'searching for collector'
		end
	end
end
contextactionservice:BindAction('find_collector', handleAction, true, Enum.KeyCode.KeypadOne)
contextactionservice:BindAction('sell_all', handleAction, true, Enum.KeyCode.KeypadTwo)
contextactionservice:BindAction('stop_buying', handleAction, true, Enum.KeyCode.KeypadThree)
contextactionservice:BindAction('buy_stuff', handleAction, true, Enum.KeyCode.KeypadFour)